[project]
name = "echomimic-v3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "Pillow",
    "einops",
    "safetensors",
    "timm",
    "tomesd",
    "torch>=2.1.2",
    "torchdiffeq",
    "torchsde",
    "decord",
    "datasets",
    "numpy",
    "scikit-image",
    "opencv-python",
    "omegaconf",
    "SentencePiece",
    "albumentations",
    "imageio[ffmpeg]",
    "imageio[pyav]",
    "tensorboard",
    "beautifulsoup4",
    "ftfy",
    "func_timeout",
    "onnxruntime",
    "accelerate>=0.25.0",
    "gradio>=3.41.2",
    "diffusers>=0.30.1",
    "transformers>=4.46.2",
    "moviepy==2.2.1",
    "tensorflow==2.15.0",
    "retina-face==0.0.17",
    "librosa",
    "mmgp",
]

[tool.ruff]
line-length = 120

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
quote-style = "double"

[tool.ruff.lint]
select = ["F"]
ignore = []

[tool.uv]
compile-bytecode = true
index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.pip]
index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
